name: Github Pages Deploy

on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.17]

    steps:
    
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and build
        run: npm install && npm run gh-build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist/landing-page # The folder the action should deploy.
          
      - name: Copy
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.AUTODEPLOYMENT }}
          src_path: 'dist/landing-page'
          dst_path: /backup/
          dst_owner: sqldropper
          dst_repo_name: copycat-action           
          
      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTODEPLOYMENT}}
        with:
          source_file: 'backup'
          destination_repo: 'sqldropper/welcome'
          user_email: 'pallintipremkumar@gmail.com'
          user_name: 'sqldropper'
          commit_message: 'Auto Update'          
